fix test
Test method TestBO4E.TestBoMapper.TestBoMapping threw exception: 
Newtonsoft.Json.JsonSerializationException: Required property 'sondersteuersatz' not found in JSON. Path 'steuerbetraege[0]', line 66, position 5.