DEV-13457: Add Steuerkennzeichen `UST_SONDER` and nullable `Sondersteuersatz` to COM Steuerbetrag (#311)
* Add UST_SONDER

* fix docstrings

* make it nullable

* json property name should be == property name (except for casing)

* fix test

Test method TestBO4E.TestBoMapper.TestBoMapping threw exception: 
Newtonsoft.Json.JsonSerializationException: Required property 'sondersteuersatz' not found in JSON. Path 'steuerbetraege[0]', line 66, position 5.

* update proto

* Make "UST_SONDER" default value

* Update proto and xml

---------

Co-authored-by: konstantin <konstantin.klein@hochfrequenz.de>
Co-authored-by: Franziska Vesely <franziska.vesely@hochfrequenz.de>
Co-authored-by: Franziska <73471037+hf-fvesely@users.noreply.github.com>